version: 2

build:
  os: ubuntu-22.04
  tools:
    # NOTE: This should be kept up to date with .ci.yml
    python: "3.11"

mkdocs:
  configuration: mkdocs.yml

python:
   install:
     - requirements: dev-requirements/mkdocs.txt
     - method: pip
       path: .
