name: Bug report
description: Found a bug? Let us know so we can fix it!
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Please make sure to search the issue tracker and have make sure it's not a duplicate.
        If it is a follow up of another issue, please make sure to specify it.
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: |
        Steps to reproduce the bug. This can also be a code snippet.
        **Make sure you have removed your bot token (if visible).**
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: expected-result
    attributes:
      label: Expected result
      description: What should have happened if the bug wasn't there?
    validations:
      required: true
  - type: textarea
    id: actual-result
    attributes:
      label: Actual result
      description: |
        What happened exactly? If you have a traceback, please provide all of it.
        **Make sure to remove ANY sensitive information (bot token, passwords, credentials, personal details, etc...)**
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: System version
      description: Please place here the output of running `python -m hikari`
      render: shell
    validations:
      required: true
  - type: textarea
    id: further-info
    attributes:
      label: Further info
      description: Any further info or images go here.
      value: "None"
  - type: markdown
    attributes:
      value: |
        By sumbitting this bug report you agree to our [Code of Conduct](https://github.com/hikari-py/hikari/blob/master/CODE_OF_CONDUCT.md)
