name: Feature request
description: Got a cool idea you would like implemented? Share it with us!
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue!

        Please make sure to search the issue tracker and have make sure it's not a duplicate.
        If it is a follow up of another issue, please make sure to specify it.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Small summary of the feature you would like to see implemented
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem will this feature solve (if any)?
    validations:
      required: true
  - type: textarea
    id: ideal-implementation
    attributes:
      label: Ideal implementation
      description: How should this feature be implemented?
      value: "To be discussed"
  - type: markdown
    attributes:
      value: |
        By sumbitting this bug report you agree to our [Code of Conduct](https://github.com/hikari-py/hikari/blob/master/CODE_OF_CONDUCT.md)
