name: CI

on: [push, pull_request]

jobs:
  test:
    strategy:
      # Allows for matrix sub-jobs to fail without canceling the rest
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.8, 3.9]
        image: [null]
        include:
          - os: ubuntu-latest
            python-version: null
            image: davfsa/stackless-python-hikari:3.8.0b3

    runs-on: ${{ matrix.os }}
    container: ${{ matrix.image }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup python
        if: ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: |
          pip install nox
          nox -s pytest
          nox -s pytest-speedups -- --cov-append

      - name: Upload report
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.python-version == '3.8' }}
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter after-build \
          --exit-code 0 \
          --id "d40e64ea0ff74713f79365fea4378ab51a2141ad4fcf0fb118496bbf560d4192"

  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Linting
        run: |
          pip install nox
          nox -s safety mypy flake8

  twemoji:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Test twemoji mapping
        run: |
          pip install nox
          nox -s twemoji-test

  pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Setup node
        uses: actions/setup-node@v1

      - name: Build pages
        run: |
          pip install nox
          nox -s pages
