name: Fragments check

on:
  pull_request:
    branches:
      - master

jobs:
  check-fragment-added:
    # Ignore for bots, they don't need it :P
    if: github.event.pull_request.user.type != 'Bot'
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4
        with:
          # `towncrier check` runs `git diff --name-only origin/main...`, which
          # needs a non-shallow clone.
          fetch-depth: 0

      - name: Setup python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8

      - name: Check if changelog fragment was added
        run: |
          pip install towncrier

          if ! towncrier check --compare-with origin/${{ github.base_ref }}; then
            echo "----------------------------------------------------"
            echo "Please refer to CONTRIBUTING.md for more information"
            exit 1
          fi
